### ISSUE TITLE
RuneLite launcher stuck on 0%

### ISSUE THREAD

**Issue by Sorkres** [runelite/launcher#18] opened 2018-05-01 10:44 UTC
When i try and open RuneLite it's always stuck on 0% and it never loads up. No .runelite folder, no logs folder. Nothing.

**Comment by korolex1** [comment] 2018-05-03 08:41
Tried everything to do with changing internet dns, restarting, redownloading etc.. Something about error in bootstrapping, Here are the logs

[launcher.log](https://github.com/runelite/launcher/files/1970125/launcher.log)

**Comment by bloodma** [comment] 2018-05-03 09:43
went through similar troubleshooting as Korolex, not sure what went wrong, was able to use the client last night. i only have the log left in my .runelite folder now. 

[launcher.log](https://github.com/runelite/launcher/files/1970308/launcher.log)

**Comment by Adam-** [comment] 2018-05-03 12:04
It would help if someone could debug why they can't connect to fastly... try executing `curl -v -H "Host: static.runelite.net" -H "User-Agent: Mozilla/5.0" runelite.github.io/bootstrap.json` (which should be equivalent to what the launcher is doing) and see what happens.

**Comment by bloodma** [comment] 2018-05-03 12:15
Hi Adam, sorry I'm not really sure what I am doing, how can I execute that line? If this is probably out of my league probably better for one of the other guys to give a shot at helping you solve it.

**Comment by ypperlig** [comment] 2018-05-03 12:32
Moufin#5476 in Discord ran the curl command and received the following output:
```
C:\Users\Chris\Downloads\curl-7.59.0\src>curl -v -H "Host: static.runelite.net" -H "User-Agent: Mozilla/5.0" runelite.github.io/bootstrap.json
*   Trying 185.199.108.153...
* TCP_NODELAY set
* connect to 185.199.108.153 port 80 failed: Timed out
*   Trying 185.199.109.153...
* TCP_NODELAY set
* connect to 185.199.109.153 port 80 failed: Timed out
*   Trying 185.199.110.153...
* TCP_NODELAY set
* connect to 185.199.110.153 port 80 failed: Timed out
*   Trying 185.199.111.153...
* TCP_NODELAY set
* connect to 185.199.111.153 port 80 failed: Timed out
* Failed to connect to runelite.github.io port 80: Timed out
* Closing connection 0
curl: (7) Failed to connect to runelite.github.io port 80: Timed out
```

**Comment by bloodma** [comment] 2018-05-03 13:04
Problem seems to be fixed as of 1.3.7.thank you.

**Comment by NetFlicks** [comment] 2018-06-21 11:21
I am getting the same issue. Can someone please help?? Runelite opens at 0% but instantly closes itself.

**Comment by Thann7** [comment] 2018-07-04 16:16
Here are my logs from trying with 64bit and All Platforms launcher. Cant seem to figure out what is going on. 

[application.log](https://github.com/runelite/launcher/files/2163826/application.log)
[launcher.log](https://github.com/runelite/launcher/files/2163827/launcher.log)

**Comment by Alexsuperfly** [comment] 2018-07-04 16:21
Thats a different exception than when it fails to fetch the official client so idk, i haven't seen it before.

**Comment by icedember** [comment] 2018-07-05 03:32
i have the same problem it seems, heres my logs
[application.log](https://github.com/runelite/launcher/files/2164827/application.log)
[launcher.log](https://github.com/runelite/launcher/files/2164828/launcher.log)

**Comment by Abextm** [comment] 2018-07-05 03:37
@icedember and @Thann7 
Since you are getting an application.log the issue is not with the launcher. Please create an issue on https://github.com/runelite/runelite

**Comment by yipers** [comment] 2018-07-06 09:36
Hi.

I have to open this again, because laucher doest get past 0.
The repo it cannnot connect, is accessible from browser.
[launcher.log](https://github.com/runelite/launcher/files/2169872/launcher.log)

**Comment by NathenSample** [comment] 2018-07-06 09:42
Yet more 403's when the client attempts to communicate with maven.

`Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact net.runelite:http-api:jar:1.4.6 from/to central (http://mvn.runelite.net/): Forbidden (403)`

**Comment by yipers** [comment] 2018-07-06 13:51
aight apparently deleting ./runelite/repositry helped.

**Comment by Adam-** [comment] 2018-07-07 16:58
We think this is fixed with 1.6.0.

**Closed by Adam-** 2018-07-07 16:58 UTC

**Comment by HaydenKeller** [comment] 2018-07-12 12:15
I'm getting the same problem. Open, creates .runelite\repository2 if I previously deleted, closes.  Once repository is created it starts and closes at 0%.

**Comment by Dodge-The-E-Bola** [comment] 2018-07-12 12:40
I have the same problem.

**Comment by MurasakiSensuYui** [comment] 2018-07-12 12:53
https://twitter.com/OldSchoolRS/status/1017364671664402432 
It looks like the OSRS servers are down, unrelated to RuneLite

**Comment by Anderzhul** [comment] 2018-07-12 12:59
^ Thanks for the link, I think this is the problem lol. I just had this issue too, when I went to check logs, launcher had no real errors just checked settings and verified a bunch of hashes, application log showed 

>  "2018-07-12 08:32:08 [RuneLite] ERROR net.runelite.client.ClientLoader - Error loading RS!
> java.net.SocketTimeoutException: connect timed out"

And a bunch of stuff about finding a connection, which makes sense if osrs servers are down.

**Comment by bardface** [comment] 2018-07-12 13:07
apparently if you pickup cash from a pk at the moment you get a max cash stack haha: 
https://twitter.com/Vancouver_07/status/1017376652827869184

**Comment by ducky3** [comment] 2018-07-23 23:21
Still having this issue, whats making it harder is that the runelite.net page wont even load. coming up with ERR_CONNECTION_RESET. Ive tried turning off firewall, tried getting off the netgear modem, reset DHS connection and turning off proxy, nothing seems to help. Did get the page to load but it didnt fully load the page and was scuffed. Eventually got to download runelite again but now wont load and is stuck on 0%
[launcher.log](https://github.com/runelite/launcher/files/2221406/launcher.log)

any advise ill be very greatful 👍 

happy scapin

**Comment by alex-512** [comment] 2018-08-18 08:52
any luck????

**Comment by Drikuzinho** [comment] 2018-09-08 00:05
i cant load my Runelite, it's the log
2018-09-07 20:55:04 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2018-09-07 20:55:07 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.security.SignatureException: Signature length not correct: got 0 but was expecting 512
	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
	at java.security.Signature$Delegate.engineVerify(Signature.java:1222)
	at java.security.Signature.verify(Signature.java:655)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:275)
	at net.runelite.launcher.Launcher.main(Launcher.java:168)

Somebody can help me?

**Comment by ridgeminer** [comment] 2018-10-06 07:46
Im having this issue but cant figure out what is wrong
[application.log](https://github.com/runelite/launcher/files/2452811/application.log)
[launcher.log](https://github.com/runelite/launcher/files/2452812/launcher.log)

**Comment by ridgeminer** [comment] 2018-10-11 06:07
> Im having this issue but cant figure out what is wrong
> [application.log](https://github.com/runelite/launcher/files/2452811/application.log)
> [launcher.log](https://github.com/runelite/launcher/files/2452812/launcher.log)

I no longer need any help. My colleges network was interfering with the launcher by blocking the website

**Comment by chip0tle** [comment] 2018-10-11 18:40
> > Im having this issue but cant figure out what is wrong
> > [application.log](https://github.com/runelite/launcher/files/2452811/application.log)
> > [launcher.log](https://github.com/runelite/launcher/files/2452812/launcher.log)
> 
> I no longer need any help. My colleges network was interfering with the launcher by blocking the website

Did you find a work-around for it? I think that I'm having a similar problem with my college's network.

**Comment by gm111** [comment] 2018-10-14 11:04
Runelite isnt loading up for me, by the sounds of it, its the same issue as whats been stated on here. when i click on the shortcut it flashes up with a bar with 0% on it but closes it self almost immediately. ive tried uninstalling, resarting my pc etc and still no luck

**Comment by ritesh3511** [comment] 2018-12-03 16:18
Just starting having the same problem with Runelite 2 days ago. Launching the game and it would show 0%  loading bar and crash immediately. Any ideas how to fix this?

**Comment by deathbeam** [comment] 2018-12-04 00:47
Try this https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by yigituran** [comment] 2018-12-16 18:41
This also happened to me 3 days ago. I'm on PC same thing happens for my laptop and mac too. I believe it's related about our IP and router settings. I can open RuneLite on my phone's personal hotspot but not on my home network.

**Comment by ridgeminer** [comment] 2018-12-16 18:48
@yigituran
Have you tried opening command prompt and see if you can get a response from the runelite website. I would just open up command prompt and ping either runelite or the runescape server to see if you are getting a response.

**Comment by ShagWelda** [comment] 2019-03-12 12:15
my RL app wont launch as of today.
after looking at my launch logs its throwing an error find worlds. any solutions?
this is the only error I can find on the logs....

" [pool-3-thread-1] WARN  n.r.c.p.w.WorldHopperPlugin - Error looking up worlds
java.net.UnknownHostException: api.runelite.net"

**Comment by ShagWelda** [comment] 2019-03-12 12:27
this error also came up

"2019-03-12 12:28:36 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.net.UnknownHostException: static.runelite.net"

**Comment by ImmortalMonk** [comment] 2019-06-18 23:43
I had to bring this up again, but I am getting the same issue where runelite is stuck at 0%. It'll open then immediately close. If I delete repository2, then it'll load up a launcher.log however, it won't actually load runelite. Is someone able to help? I've attached the Laucher.log
[launcher.log](https://github.com/runelite/launcher/files/3303838/launcher.log)

**Comment by ImmortalMonk** [comment] 2019-06-19 03:19
@Adam- any way to help? 
Thanks in advance
